import turtle
turtle.shape('circle')
finn = turtle.clone()
finn.shape('arrow')
turtle.bgcolor('purple')
turtle.pencolor('yellow')
turtle.color('yellow')
turtle.pensize(3)
turtle.goto(0,100)
turtle.left(90)
turtle.goto(-50,100)
turtle.color('white')
turtle.left(90)
turtle.goto(-50,0)
